---
title: "kümeleme"
author: "ilke"
date: "2024-01-29"
output: html_document
---

## 1. Kütüphanelerin Yüklenmesi

```{r, warning=FALSE, message=FALSE}
library(readr)
library(tidyverse)
library(tidyr)
library(dendextend)
library(knitr)
library(gridExtra)
library(ggplot2)
library(VIM)
library(corrplot)
library(car)
library(ResourceSelection)
library(glmulti)
library(tree)
library(randomForest)
library(ISLR)
library(class)
library(pROC)
library(gtools)
library(tidyverse)
library(GGally)
library(superml)
library(caret)
library(Boruta)
library("stringr")
library("tidyr")
library("readr")
library("here")
library("skimr")
library("janitor")
library("lubridate")
library(gridExtra)
library(ggplot2)
library(VIM)
library(corrplot)
library(car)
library(ResourceSelection)
library(glmulti)
library(tree)
library(randomForest)
library(ISLR)
library(class)
library(pROC)
library(gtools)
library(tidyverse)
library("scales")
library("ggcorrplot")
library("ggrepel")
library("forcats")
library("corrgram")
library(tidymodels)
library(baguette)
library(discrim)
library(bonsai)
library(ResourceSelection)
library(kableExtra)
library(broom)
library(dplyr)
library(caret)
library(tidyr)
library(corrplot)
library("Hmisc")
library(psych)
library(factoextra)
library("DescTools")
library(ResourceSelection)
library(haven)
library(effectsize)
library(rstatix)
library(ggpubr)
library(biotools)
library(PerformanceAnalytics)
library(heplots)
library(gplots)
```

```{r,warning=FALSE,message=FALSE}
clean_df <- read.csv('/home/ilke/Downloads/clean_heart.csv')
```
## 10.Kümeleme

### 10.1 Hiyerarşik Kümeleme


```{r}
h_kume <- clean_df[, c("Age","RestingBP","Cholesterol","MaxHR","Oldpeak")]
h_kumee <- scale(h_kume)
# Korelasyon matrisinin incelenmesi
rcorr(as.matrix(h_kume),type="pearson") 
```

```{r}
# Hiyerarsik Kümeleme
d <- dist(h_kume, method = "euclidean") # uzaklik matrisi
fit <- hclust(d, method="ward.D") # method= "single", "complete", "average", "ward.D", "centroid"
dend<-as.dendrogram(fit) # Dendogram çizimi
plot(dend)

plot(color_branches(dend, k=4))
```

### 10.2 K-Means

```{r}
h_kume <- scale(h_kume)
fviz_nbclust(h_kume, kmeans, method = "wss")
fviz_nbclust(h_kume, kmeans, method = "silhouette")
```

```{r}

set.seed(95739487) 
km.res <- kmeans(h_kume,2, iter.max=100, algorithm="Lloyd")### i
t(km.res$centers) 
```

```{r}
library(cluster)
clusplot(h_kume, km.res$cluster, main='2D representation of the Cluster solution',
         color=TRUE, shade=TRUE,
         labels=2, lines=0)
```

